In [1]:
import numpy as np

# Create a 1D array
a = np.arange(1,10)
print(a)
print(np.shape(a))
print(np.dtype(a))
print(np.sum(a))

[1 2 3 4 5 6 7 8 9]
(9,)
int64
45


In [8]:
# Create a 3×4 matrix filled with zeros, and a 2×2 matrix filled with ones. Print both.

a1 = np.zeros((3,4))
a2 = np.ones((2,2))

print(a1)
print(a2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [16]:
# Given the array [10, 20, 30, 40, 50, 60, 70], extract elements from index 2 to 5 (inclusive), and also get the last 3 elements.

a = np.array([10, 20, 30, 40, 50, 60, 70])
print(a[2:6])
print(a[-1:-4:-1])

[30 40 50 60]
[70 60 50]


In [20]:
# Create an array of numbers from 1 to 12, then reshape it into a 3×4 matrix and a 2×6 matrix.

a1 = np.arange(1,13).reshape(3,4)
a2 = np.arange(1,13).reshape(2,6)

print(a1)
print(a2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [22]:
# Create two arrays: a = [1, 2, 3, 4] and b = [10, 20, 30, 40]. Compute their element-wise sum, difference, and product.

a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

print(a+b)
print(a-b)
print(a*b)

[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]


In [27]:
# Create a 1D array of random integers between 1 and 50 (size 10). Extract all elements greater than 25 using boolean indexing.

a = np.random.randint(1,51,10)
print(a[a>25])


[26 33 35 33]


In [30]:
# Create two 3×3 matrices with random integers. Compute their matrix product (not element-wise), and also find the transpose of the first matrix.

a1 = np.random.randint(1,30,9).reshape(3,3)
a2 = np.random.randint(1,30,9).reshape(3,3)

[[18 25  8]
 [28 12 18]
 [22  3 27]]
[[ 8  8 15]
 [23  6 23]
 [ 1  6 10]]


In [35]:
print(np.dot(a1,a2))
print(a1.T)

[[727 342 925]
 [518 404 876]
 [272 356 669]]
[[18 28 22]
 [25 12  3]
 [ 8 18 27]]


In [51]:
# Create a 4×4 matrix of random floats. Find the mean, median, standard deviation, min, and max — for the entire matrix and also per column.

a = np.random.random(16).reshape(4,4)

print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.max(a))
print(np.min(a))

0.3699958440579213
0.28319784917827173
0.2630727307461191
0.9593387253649747
0.11722710996130425


In [55]:
# Create two 2×3 arrays. Stack them vertically (resulting in 4×3) and horizontally (resulting in 2×6).

a1 = np.arange(6).reshape(2,3)
a2 = np.arange(6,12).reshape(2,3)

print(a1)
print(a2)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [59]:
np.vstack([a1,a2])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [60]:
np.hstack([a1,a2])

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [64]:
# Create a 3×3 matrix. Subtract the column-wise mean from each column (center the data). This is a fundamental step in data science preprocessing.

a = np.random.randint(1,30,9).reshape(3,3)
a

array([[20, 21,  6],
       [ 6, 16, 21],
       [24, 25, 22]])

In [68]:
mean = np.mean(a, axis = 0)
print(a-mean)

[[  3.33333333   0.33333333 -10.33333333]
 [-10.66666667  -4.66666667   4.66666667]
 [  7.33333333   4.33333333   5.66666667]]


In [69]:
# Create a 5×5 matrix of random integers. Extract the elements at positions (0,1), (2,3), and (4,4) in one single indexing operation.

a = np.random.randint(1,100,25).reshape(5,5)
a

array([[73, 70,  9,  8, 98],
       [ 6, 45, 91, 76, 66],
       [21, 60, 67, 95,  3],
       [55, 18, 72, 93, 65],
       [45, 55, 63, 98, 63]])

In [72]:
print(a[[0,2,4],[1,3,4]])

[70 95 63]


In [75]:
# Create a 3×3 matrix. Compute its determinant, inverse, and solve the linear system Ax = b where b = [1, 2, 3].

A = np.random.randint(1,30,9).reshape(3,3)
A

array([[ 7, 27, 19],
       [ 1, 29, 25],
       [ 6,  7, 13]])

In [83]:
# determinant
det = np.round(np.linalg.det(A))
det

np.float64(1940.0)

In [79]:
# inverse
print(np.linalg.inv(A))

[[ 0.10412371 -0.11237113  0.06391753]
 [ 0.07061856 -0.01185567 -0.08041237]
 [-0.08608247  0.05824742  0.09072165]]


In [85]:
#  AX = B
B = np.array([1,2,3])

X = (1/det) * (A.T * B)

print(X)


[[0.00360825 0.00103093 0.00927835]
 [0.01391753 0.02989691 0.01082474]
 [0.00979381 0.0257732  0.02010309]]


In [89]:
# Write a function that returns x² + 2x + 1 for a given x. Apply it to an array [−3, −2, −1, 0, 1, 2, 3] without using any Python for loop.

a = np.array([-3, -2, -1, 0, 1, 2, 3])

def f(x):
  return x**2 + 2*x +1

x = f(a)
x


array([ 4,  1,  0,  1,  4,  9, 16])