In [2]:
import numpy as np

a = np.array([1,2,3])
print(a)
print(type(a))


[1 2 3]
<class 'numpy.ndarray'>


In [3]:
# own datatype array

np.array([1,2,3],dtype=float)


array([1., 2., 3.])

In [4]:
np.array([0,1,2], dtype=bool)

array([False,  True,  True])

In [5]:
#  np.arange

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# np.reshape

m = np.arange(10).reshape(2,5)
print(m)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
# np.ones

np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [8]:
# np.zeros

np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [9]:
# np.random

np.random.random((2,2))

array([[0.63547543, 0.41796504],
       [0.04721279, 0.82975022]])

In [10]:
# np.linspace

np.linspace(-10,10,12,dtype=int)

array([-10,  -9,  -7,  -5,  -3,  -1,   0,   2,   4,   6,   8,  10])

In [11]:
# np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Atributes

In [12]:
a1 = np.arange(10,dtype=float)
a2 = np.arange(12).reshape(2,6)
a3 = np.arange(8).reshape(2,2,2)

In [13]:
# ndin -> no.of dimensions

a3.ndim

3

In [14]:
# shape ->

a3.shape

(2, 2, 2)

In [15]:
# size -> returns total no of items

a3.size

8

In [16]:
# itemsize -> returns item memory size

a1.itemsize

8

In [17]:
# dtype

print(a1.dtype)
print(a2.dtype)

float64
int64


Changing Datatype

In [25]:

a3.astype(np.int32)
a3.dtype

dtype('int64')

**Array Operations**

In [26]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [40]:
# scalar
#arithmetic

# a1 + 2
# a1 *2
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [44]:
# relational

a2 == 18

array([[False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [52]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

#  Array Functions


In [121]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

a1

array([[29., 38., 92.],
       [18., 81., 96.],
       [68., 54.,  5.]])

In [122]:
# max
np.max(a1)

np.float64(96.0)

In [123]:
# min
np.min(a1)

np.float64(5.0)

In [124]:
# sum

np.sum(a1)

np.float64(481.0)

In [125]:
# product
np.prod(a1)

np.float64(260537868472320.0)

In [126]:
# axis = 1 for each row |||| axis = 0 for each column

np.max(a1, axis = 1)

array([92., 96., 68.])

##### Statistical Functions

In [127]:
# mean/median/std/var

np.mean(a1)

np.float64(53.44444444444444)

In [128]:
# DOT Product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

##### Indexing and Slicing

In [129]:
a1 = np.arange(5)
a1
print(a1[-1])


4


In [130]:
# 2d array

a2 = np.arange(12).reshape(3,4)
print(a2[2,3])

11


In [131]:
# 3d array

a3 = np.arange(27).reshape(3,3,3)
print(a3[1,2,1])


16


In [132]:
# SLICING

print(a1)
print(a1[0:3])

[0 1 2 3 4]
[0 1 2]


In [133]:
print(a2)
print("\n")
print(a2[:,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[ 2  6 10]


In [134]:
print(a2[1:,1:3])

[[ 5  6]
 [ 9 10]]


In [135]:
print(a2[0:3:2 ,0:5:3])

[[ 0  3]
 [ 8 11]]


In [136]:
print(a2[::2, 1::2])

[[ 1  3]
 [ 9 11]]


In [141]:
print(a2[1, ::2])

[4 6]


In [144]:
print(a2[0:2, 1:])

[[1 2 3]
 [5 6 7]]


In [145]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [151]:
print(a3[1, :,1])

[10 13 16]


In [152]:
print(a3[2, 1:,1:])

[[22 23]
 [25 26]]


In [155]:
print(a3[::2, 0,::2])

[[ 0  2]
 [18 20]]


## Iterating


In [156]:
a1

array([0, 1, 2, 3, 4])

In [157]:
for i in a1:
  print(i)

0
1
2
3
4


In [158]:
 a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [166]:
for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [161]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [165]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [167]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [170]:
# transpose
# np.transpose(a2)

a2.T



array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [172]:
# ravel -> converts to 1D

a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [176]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

#Spliting

In [180]:
a = np.arange(16).reshape(4,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [185]:
# horizontal spliting
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [186]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [194]:
# vertical spliting
np.vsplit(a,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]