<a href="https://colab.research.google.com/github/jiban-khatri/Numpy/blob/main/numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,20).reshape(5,4)

In [ ]:
a




array([53, 83, 36, 70, 88, 42, 93, 30, 35, 78, 75, 78, 97, 75, 33])

In [ ]:
b

array([[77, 45, 88, 21],
       [73,  6, 98, 57],
       [92,  7, 68, 38],
       [ 8, 79, 97, 21],
       [53,  1, 21, 51]])

In [ ]:
# sort

np.sort(a)

array([30, 33, 35, 36, 42, 53, 70, 75, 75, 78, 78, 83, 88, 93, 97])

In [ ]:
# side wise
np.sort(b, axis = 1)

array([[21, 45, 77, 88],
       [ 6, 57, 73, 98],
       [ 7, 38, 68, 92],
       [ 8, 21, 79, 97],
       [ 1, 21, 51, 53]])

In [ ]:
# down wise
np.sort(b, axis = 0)

array([[ 8,  1, 21, 21],
       [53,  6, 68, 21],
       [73,  7, 88, 38],
       [77, 45, 97, 51],
       [92, 79, 98, 57]])

In [ ]:
#  descending order
print(np.sort(a)[::-1])


[97 93 88 83 78 78 75 75 70 53 42 36 35 33 30]


In [ ]:
# APPEND

a

array([53, 83, 36, 70, 88, 42, 93, 30, 35, 78, 75, 78, 97, 75, 33])

In [ ]:
np.append(a,200)

array([ 53,  83,  36,  70,  88,  42,  93,  30,  35,  78,  75,  78,  97,
        75,  33, 200])

In [ ]:
b

array([[77, 45, 88, 21],
       [73,  6, 98, 57],
       [92,  7, 68, 38],
       [ 8, 79, 97, 21],
       [53,  1, 21, 51]])

In [ ]:
np.append(b,np.random.randint(1,50,5).reshape(5,1), axis = 1)

array([[77, 45, 88, 21, 11],
       [73,  6, 98, 57, 36],
       [92,  7, 68, 38, 34],
       [ 8, 79, 97, 21,  5],
       [53,  1, 21, 51, 29]])

In [ ]:
# CONCATENATE

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d), axis = 0) #down wise

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np. concatenate((c,d), axis = 1)  #sidewise

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [ ]:
# NP.UNIQUE()

e = np.array([1,2,3,4,2,1,6,3,6])
np.unique(e)


array([1, 2, 3, 4, 6])

In [ ]:
# np.expand_dims

a

array([53, 83, 36, 70, 88, 42, 93, 30, 35, 78, 75, 78, 97, 75, 33])

In [ ]:
np.expand_dims(a, axis=1)

array([[53],
       [83],
       [36],
       [70],
       [88],
       [42],
       [93],
       [30],
       [35],
       [78],
       [75],
       [78],
       [97],
       [75],
       [33]])

In [ ]:
#  np.where -> returns index position acc to condition given

a

array([53, 83, 36, 70, 88, 42, 93, 30, 35, 78, 75, 78, 97, 75, 33])

In [ ]:
# value > 50

np.where(a>50)

(array([ 0,  1,  3,  4,  6,  9, 10, 11, 12, 13]),)

In [ ]:
#  replace grater than 50 with 0
# ----> np.where(condition, true, false)

np.where(a>50, 0, a)

array([ 0,  0, 36,  0,  0, 42,  0, 30, 35,  0,  0,  0,  0,  0, 33])

In [ ]:
#  replaces all even numbers with 1
np.where(a%2==0, 1, a)

array([53, 83,  1,  1,  1,  1, 93,  1, 35,  1, 75,  1, 97, 75, 33])

In [ ]:
# np.argmax -> returns indices of the max element of the array in a particular axis

a

array([53, 83, 36, 70, 88, 42, 93, 30, 35, 78, 75, 78, 97, 75, 33])

In [ ]:
print(np.argmax(a))

12


In [ ]:
b

array([[77, 45, 88, 21],
       [73,  6, 98, 57],
       [92,  7, 68, 38],
       [ 8, 79, 97, 21],
       [53,  1, 21, 51]])

In [ ]:
print(np.argmax(b, axis = 0))

[2 3 1 1]


In [ ]:
# np.cumsum -> cumulative sum
a


array([53, 83, 36, 70, 88, 42, 93, 30, 35, 78, 75, 78, 97, 75, 33])

In [ ]:
np.cumsum(a)

array([ 53, 136, 172, 242, 330, 372, 465, 495, 530, 608, 683, 761, 858,
       933, 966])

In [ ]:
b

array([[77, 45, 88, 21],
       [73,  6, 98, 57],
       [92,  7, 68, 38],
       [ 8, 79, 97, 21],
       [53,  1, 21, 51]])

In [ ]:
np.cumsum(b, axis = 1)

array([[ 77, 122, 210, 231],
       [ 73,  79, 177, 234],
       [ 92,  99, 167, 205],
       [  8,  87, 184, 205],
       [ 53,  54,  75, 126]])

In [ ]:
# cumprod
a

array([53, 83, 36, 70, 88, 42, 93, 30, 35, 78, 75, 78, 97, 75, 33])

In [ ]:
np.cumprod(a)

array([                  53,                 4399,               158364,
                   11085480,            975522240,          40971934080,
              3810389869440,      114311696083200,     4000909362912000,
         312070930307136000,  4958575699325648384,  -612721000500009984,
       -4093704827372313600,  6566787200138857472, -4656951279932322816])

In [ ]:
# np.percentile

a

array([53, 83, 36, 70, 88, 42, 93, 30, 35, 78, 75, 78, 97, 75, 33])

In [ ]:
np.percentile(a,100)

np.float64(97.0)

In [ ]:
  # np.histogram
a

array([96, 73, 90, 87, 66, 38, 38,  3, 22, 18, 40, 37, 20, 26, 32])

In [ ]:
np.histogram(a, bins=[0,30,60,90,120])


(array([0, 6, 7, 2]), array([  0,  30,  60,  90, 120]))

In [ ]:
# np.corrcoef

sal = np.array([20000,40000,320000,25000])
exp = np.array([1,3,2,1])

np.corrcoef(sal,exp)

array([[1.        , 0.22939334],
       [0.22939334, 1.        ]])

In [ ]:
# np.isin
a

array([96, 73, 90, 87, 66, 38, 38,  3, 22, 18, 40, 37, 20, 26, 32])

In [ ]:
items = [10,20,30,40,50,70,80,90]
np.isin(a,items)


array([False, False,  True, False, False, False, False, False, False,
       False,  True, False,  True, False, False])

In [ ]:
# np.flip
a


array([96, 73, 90, 87, 66, 38, 38,  3, 22, 18, 40, 37, 20, 26, 32])

In [ ]:
np.flip(a)

array([32, 26, 20, 37, 40, 18, 22,  3, 38, 38, 66, 87, 90, 73, 96])

In [ ]:
b

array([[27,  1, 70, 40],
       [69, 49, 87, 67],
       [48, 18, 35,  8],
       [11, 85, 21,  2],
       [ 6, 58, 70, 41]])

In [ ]:
np.flip(b)

array([[41, 70, 58,  6],
       [ 2, 21, 85, 11],
       [ 8, 35, 18, 48],
       [67, 87, 49, 69],
       [40, 70,  1, 27]])

In [ ]:
# delete
a

array([96, 73, 90, 87, 66, 38, 38,  3, 22, 18, 40, 37, 20, 26, 32])

In [ ]:
np.delete(a,3)

array([96, 73, 90, 66, 38, 38,  3, 22, 18, 40, 37, 20, 26, 32])